version: '3.3'
services:
    valtimo_keycloak:
        image: ritense/valtimo-keycloak:0.0.4
        container_name: valtimo_keycloak
        ports:
            - 8081:8080
    gzac-database:
        container_name: gzac-database
        image: mysql/mysql-server:8.0.28-1.2.7-server
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: gzac
            MYSQL_USER: gzac
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        command: [
            "--default-authentication-plugin=mysql_native_password",
            "--lower_case_table_names=1",
            "--collation-server=utf8mb4_unicode_ci",
            "--character-set-server=utf8mb4",
            "--explicit_defaults_for_timestamp",
            "--ssl=false",
            "--innodb_flush_method=O_DIRECT",
            "--sql_mode=NO_ENGINE_SUBSTITUTION"
        ]
        volumes:
            - gzac-database-data:/var/lib/mysql # persist data even if container shuts down
    
volumes:
    gzac-database-data:
