version: '3.9'
services:
  openzaak:
    image: openzaak/open-zaak:1.5.0
    container_name: openzaak
    platform: linux/amd64
    environment:
      - DB_HOST=openzaak-postgis
      - SECRET_KEY=veryRestrictedSecretKey
      - DB_USER=openzaak
      - DB_PASSWORD=openzaak
      - DB_NAME=openzaak
      - CACHE_DEFAULT=openzaak-redis:6379/0
      - CACHE_AXES=openzaak-redis:6379/0
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
      - DJANGO_SUPERUSER_PASSWORD=admin
      - SENDFILE_BACKEND=django_sendfile.backends.simple
    ports:
      - "8001:8000"

  openzaak-postgis:
    image: mdillon/postgis:11
    container_name: openzaak-postgis
    platform: linux/amd64
    environment:
      - POSTGRES_USER=openzaak
      - POSTGRES_PASSWORD=openzaak
      - POSTGRES_DB=openzaak
    ports:
      - "5433:5432"
    volumes:
      - ./imports/open-zaak:/docker-entrypoint-initdb.d

  openzaak-redis:
    image: redis:6.2.6
    container_name: openzaak-redis
